"""Render generated document text into a formatted .docx and extract text back.

Formatting heuristics are deliberately conservative: legal text generated by
Claude is plain paragraphs; short ALL-CAPS lines are treated as headings.
"""
from __future__ import annotations

import io

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH


def _is_heading(line: str) -> bool:
    stripped = line.strip()
    return 0 < len(stripped) <= 80 and stripped == stripped.upper() and any(c.isalpha() for c in stripped)


def render_docx(text: str, title: str | None = None) -> bytes:
    """Convert plain document text into .docx bytes."""
    document = Document()
    if title:
        heading = document.add_paragraph()
        heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = heading.add_run(title)
        run.bold = True

    for line in text.split("\n"):
        if not line.strip():
            continue
        paragraph = document.add_paragraph()
        run = paragraph.add_run(line.strip())
        if _is_heading(line):
            run.bold = True

    buffer = io.BytesIO()
    document.save(buffer)
    return buffer.getvalue()


def extract_text(docx_bytes: bytes) -> str:
    """Extract paragraph text from .docx bytes (used for [MISSING] checks,
    redline bases and RAG context)."""
    document = Document(io.BytesIO(docx_bytes))
    return "\n".join(p.text for p in document.paragraphs)
